### ISSUE TITLE
As end-user I would like to see on parkig.bz.it parking stations that are positioned on the same point properly visualized on map

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/parking-app#11]
Issue:

![Image](https://github.com/user-attachments/assets/c4134ad2-8e7d-4183-b657-cf8daf3d4c53)

In this example, only one of the three parking stations related to the ParkingLocation "Train Station" are visualized on the map

**Comment by dulvui** [comment]
I checked the code now and the library doesn't support something similar to analytics, so a custom cluster view needs to be implemented. It is not a huge effort but needs some time.

**Comment by dulvui** [comment]
Now all 3 parkings of Bressanone are visible on testing https://parking.opendatahub.testingmachine.eu/?location=bressanone
![Image](https://github.com/user-attachments/assets/8fc9807f-4b88-4654-acbc-0928a3ab6011)

**Comment by rcavaliere** [comment]
Perfect! Let's go in production, @dulvui

**Comment by dulvui** [comment]
@rcavaliere great, now it is live in production https://parking.opendatahub.com/?location=bressanone
