### ISSUE TITLE
As a parking APP user I would like to see the nominal capacity of non real-time parking areas, if available

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/parking-app#9]

**Comment by dulvui** [comment]
@rcavaliere I checked now and the offline parking areas are coming from the tourism API and there we don't have any capacity or at least I couldn't find any.
Probably @RudiThoeni can confirm if there is a capacity or not

**Comment by RudiThoeni** [comment]
@rcavaliere @dulvui 
I checked on the tourism api the capacity of a Poi Tagged as Parking stations (LTS), unfortunately this info is not opendata....
However i checked how many of the data has this info set, at the moment from 460 Pois tagged with Parking station, 15 have this information inserted ;)

**Comment by rcavaliere** [comment]
This is a pity, really do not understand why such a metadata should not be open. If this is the situation, let's close the issue, since we wont' be able to see this.
